version: "3.8"
services:
  backend:
    build: ./Techdome-backend-main
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./Techdome-frontend-main
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
